<a href="https://colab.research.google.com/github/schatz06/Thesis/blob/Bio_embeddings/embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Install and import embedders

In [ ]:
pip install bio-embeddings[all]

In [ ]:
from bio_embeddings.embed import seqvec_embedder , prottrans_bert_bfd_embedder

In [ ]:
embedder_seqvec = seqvec_embedder.SeqVecEmbedder()
embedder_protbert= prottrans_bert_bfd_embedder.ProtTransBertBFDEmbedder()
max_seq = 1538 # larget sequences in the datasets

Generic method to extract ProtBert Embeddings

In [41]:
def extract_protBert(max_seq,lines,path,embedder_protbert):
  max_sequence = max_seq
  count = 1 # current line
  target_name = 1 # target line that has the name of the protein 
  target_primary = 2 # target line that has the primary structure 
  for line in lines:
    if count == target_name:
      line = line.replace("\n","") # remove the newline character in the end of the string 
      path_to_save = path + '/' + line+ ".txt"
      target_name +=3
    if count == target_primary:
      line = line.replace("\n","") # remove the newline character in the end of the string 
      embedding_protbert = embedder_protbert.embed(line) # extract the embeddings 
      padding = max_sequence - embedding_protbert.shape[0]
      embedding_protbert = np.pad(embedding_protbert,((0,padding),(0,0)),mode='constant',constant_values = 0) # apply zero padding at the end 
      savetxt(path_to_save,embedding_protbert, delimiter=',') # save the embedding in a new txt in a directory 
      target_primary +=3
    count+=1

Generic method to extract SeqVec Embeddings 

In [40]:
def extract_seqVec(max_seq,lines,path,embedder_seqvec):
  max_sequence = max_seq 
  count = 1 # current line
  target_name = 1 # target line that has the name of the protein 
  target_primary = 2 # target line that has the primary structure 
  for line in lines:
    if count == target_name:
      line = line.replace("\n","") # remove the newline character in the end of the string 
      path_to_save = path + '/' + line+ ".txt"
      target_name +=3
    if count == target_primary:
      line = line.replace("\n","") # remove the newline character in the end of the string 
      embedding_seqvec = embedder_seqvec.embed(line) # extract the embeddings 
      padding = max_sequence - embedding_seqvec.shape[1]
      embedding_seqvec = np.pad(embedding_seqvec,((0,0)(0,padding),(0,0)),mode='constant',constant_values = 0) # apply zero padding at the end 
      embedding_seqvec = embedding_seqvec.reshape(arr.shape[0], -1) # convert 3d matrix to 2d matrix in order to be able to save it 
      savetxt(path_to_save,embedding_seqvec, delimiter=',') # save the embedding in a new txt in a directory 
      target_primary +=3
    count+=1

Import packages

In [28]:
import numpy as np
from numpy import asarray
from numpy import savetxt
import os

Create new directories to save the embeddings 

In [34]:
path = os.getcwd() # get the current directory
path_CASP_protBert = path + '/CASP13_ProtBert' 
path_CASP_seqVec = path + '/CASP13_SeqVec' 
path_CB513_protBert = path + '/CB513_ProtBert' 
path_CB513_seqVec = path + '/CB513_SeqVec' 
path_PISCES_protBert = path + '/PISCES_ProtBert' 
path_PISCES_seqVec = path + '/PISCES_SeqVec'  
os.mkdir(path_CASP_protBert)
os.mkdir(path_CASP_seqVec)
os.mkdir(path_CB513_protBert)
os.mkdir(path_CB513_seqVec)
os.mkdir(path_PISCES_protBert)
os.mkdir(path_PISCES_seqVec)

Open files/ Create pointers

In [20]:
casp = open("CASP13_sorted.txt","r")
cb513 = open("CB513_sorted.txt","r")
pisces = open("PISCES_sorted.txt","r")

Read lines

In [21]:
casp_lines = casp.readlines()
cb513_lines = cb513.readlines()
pisces_lines = pisces.readlines()

Extract SeqVec and ProtBert embeddings for CASP13

In [ ]:
extract_protBert(max_seq,casp_lines,path_CASP_protBert,embedder_protbert)
extract_seqVec(max_seq,casp_lines,path_CASP_seqVec,embedder_seqvec)

Extract SeqVec and ProtBert embeddings for CB513




In [50]:
extract_protBert(max_seq,cb513_lines,path_CB513_protBert,embedder_protbert)
extract_seqVec(max_seq,cb513_lines,path_CB513_seqVec,embedder_seqvec)

Extract SeqVec and ProtBert embeddings for PISCES

In [51]:
extract_protBert(max_seq,pisces_lines,path_PISCES_protBert,embedder_protbert)
extract_seqVec(max_seq,pisces_lines,path_PISCES_seqVec,embedder_seqvec)

How to load a numpy array

In [26]:
from numpy import loadtxt
# load array
data = loadtxt('/content/> 6btc_1_protBert.txt', delimiter=',')
print(data.shape)

(85, 1024)


Load a 2d array and convert it to a 3d array

In [44]:

import numpy as gfg 
  
  
arr = gfg.random.rand(5, 4, 3) 
print(arr)  
# reshaping the array from 3D 
# matrice to 2D matrice. 
arr_reshaped = arr.reshape(arr.shape[0], -1) 
  
# saving reshaped array to file. 
gfg.savetxt("geekfile.txt", arr_reshaped) 
  
# retrieving data from file. 
loaded_arr = gfg.loadtxt("geekfile.txt") 
  
# This loadedArr is a 2D array, therefore 
# we need to convert it to the original 
# array shape.reshaping to get original 
# matrice with original shape. 
load_original_arr = loaded_arr.reshape( 
    loaded_arr.shape[0], loaded_arr.shape[1] // arr.shape[2], arr.shape[2]) 
  
# check the shapes: 
print("shape of arr: ", arr.shape) 
print("shape of load_original_arr: ", load_original_arr.shape) 
  
# check if both arrays are same or not: 
if (load_original_arr == arr).all(): 
    print("Yes, both the arrays are same") 
else: 
    print("No, both the arrays are not same") 
print(arr)

[[[5.59641680e-01 1.04741309e-01 5.75835964e-01]
  [6.75527359e-02 9.07020079e-01 1.10047396e-01]
  [7.08386749e-01 6.54379386e-01 6.31913811e-01]
  [5.78172162e-01 7.41043085e-01 1.54197191e-01]]

 [[7.50579679e-01 9.51992200e-01 2.31803001e-01]
  [9.27358813e-01 7.51183852e-04 4.24454992e-01]
  [4.91737210e-01 8.05436766e-01 6.32693588e-01]
  [7.30339310e-01 8.15897248e-01 2.99986753e-01]]

 [[9.64990760e-01 4.24508620e-01 4.90063285e-04]
  [6.34545566e-01 1.39352145e-01 1.04035814e-01]
  [9.05295986e-01 2.02714770e-01 3.70547705e-01]
  [3.61573961e-01 9.65699508e-01 1.14306991e-01]]

 [[7.61130947e-01 8.07126092e-01 5.21232029e-01]
  [2.59380502e-01 4.16580988e-01 3.18499792e-01]
  [1.02119345e-01 4.31205357e-01 3.26473537e-01]
  [5.57022271e-02 3.54290176e-01 3.32199272e-01]]

 [[8.42373717e-01 8.20657628e-01 7.17607558e-01]
  [8.70116409e-01 5.97393794e-01 1.70498046e-01]
  [2.71352235e-01 9.13199151e-01 4.67510070e-02]
  [1.21580420e-02 9.99296114e-02 7.81023774e-01]]]
shape of a